
[env]
# use for build arm64 in docker
# CROSS_CONTAINER_IN_CONTAINER = true

[tasks.rd]
alias = "rundev"
[tasks.rundev]
command = "cargo"
args = ["run", "--features", "bin-tui", "--bin", "clashtui"]

[tasks.ci]
dependencies = ["setup-mihomo", "ci-flow"]
script = ["rm mihomo", "rm Doc/clash_test/cache.db"]

[tasks.ci.windows]
# ignore this shit
dependencies = []
script = ""

[tasks.setup-mihomo.windows]
script_runner = "pwsh"
script_extension = "ps1"
script = '''
    curl --output mihomo.zip -L https://github.com/MetaCubeX/mihomo/releases/download/v1.18.4/mihomo-windows-amd64-v1.18.4.zip
    7z x mihomo.zip
    mihomo-windows-amd64.exe -d Doc/clash_test -f Doc/clash_test/config.yaml &
'''
[tasks.setup-mihomo.linux]
script = '''
    curl --output mihomo.gz -L https://github.com/MetaCubeX/mihomo/releases/download/v1.18.4/mihomo-linux-amd64-v1.18.4.gz
    gunzip mihomo.gz
    chmod +x mihomo
    nohup ./mihomo -d Doc/clash_test -f Doc/clash_test/config.yaml > /dev/null &
'''


[tasks.release.windows]
dependencies = ["clear-artifacts", "amd64"]
script_runner = "@shell"
script = [
    "mkdir artifacts",
    "cp target/release/clashtui.exe artifacts/clashtui.release.exe",
    "cp target/debug/clashtui.exe artifacts/clashtui.debug.exe",
]
[tasks.release.linux]
dependencies = ["clear-artifacts", "arm64", "amd64", "build_deb"]
script = '''
    mkdir artifacts
    cp target/debian/*.deb artifacts/clashtui.deb
    cp target/release/clashtui artifacts/clashtui.amd64.release
    cp target/debug/clashtui artifacts/clashtui.amd64.debug
    cp target/aarch64-unknown-linux-gnu/release/clashtui artifacts/clashtui.arm64.release
    cp target/aarch64-unknown-linux-gnu/debug/clashtui artifacts/clashtui.arm64.debug
'''

[tasks.clear-artifacts]
private = true
script_runner = "@shell"
ignore_errors = true
script = ["rm -r artifacts"]

[tasks.build_deb]
install_crate = "cargo-deb"
command = "cargo"
args = ["deb", "--", "--bin", "clashtui", "--all-features"]

[tasks.arm64]
install_crate = "cross"
script = '''
    cross build --bin clashtui --all-features --target=aarch64-unknown-linux-gnu
    cross build --bin clashtui --all-features --release --target=aarch64-unknown-linux-gnu
'''

[tasks.amd64]
script = '''
    cargo build --bin clashtui --all-features
    cargo build --bin clashtui --all-features --release
'''


[tasks.upx.linux]
dependencies = ["release"]
script = '''
    chmod +x artifacts/*
    curl -OL https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-amd64_linux.tar.xz
    tar -xf upx-4.2.4-amd64_linux.tar.xz
    rm upx-4.2.4-amd64_linux.tar.xz
    cp ./upx-4.2.4-amd64_linux/upx .
    rm -r ./upx-4.2.4-amd64_linux
    ./upx artifacts/*.release artifacts/*.debug
    rm upx
'''

[tasks.upx.windows]
dependencies = ["release"]
script = '''
    curl -OL https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-win64.zip
    tar -xf upx-4.2.4-win64.zip
    cp ./upx-4.2.4-win64/upx.exe .
    rm -r ./upx-4.2.4-win64
    upx.exe artifacts/*.exe
    rm upx.exe
'''
