#[derive(Clone)]
pub struct Profile {
    pub name: String,
    pub dtype: ProfileType,
}

impl Default for Profile {
    fn default() -> Self {
        Self {
            name: "Unknown".into(),
            dtype: ProfileType::File,
        }
    }
}

#[cfg_attr(test, derive(PartialEq))]
#[derive(Debug, serde::Serialize, serde::Deserialize, Clone)]
pub enum ProfileType {
    /// local import
    File,
    /// download url
    Url(String),
    /// generated by template
    Generated(String),
    Github {
        url: String,
        token: String,
    },
    GitLab {
        url: String,
        token: String,
    },
}

type ProfileDataBase = std::collections::HashMap<String, ProfileType>;

#[cfg_attr(test, derive(PartialEq))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default)]
/// manage profiles
pub struct ProfileManager {
    current_profile: String,
    profiles: ProfileDataBase,
}
impl ProfileManager {
    pub fn insert<S: AsRef<str>>(&mut self, name: S, dtype: ProfileType) -> Option<Profile> {
        self.profiles
            .insert(name.as_ref().into(), dtype)
            .map(|dtype| Profile {
                name: name.as_ref().to_string(),
                dtype,
            })
    }
    pub fn get<S: AsRef<str>>(&self, name: S) -> Option<Profile> {
        self.profiles
            .get(name.as_ref())
            .cloned()
            .map(|dtype| Profile {
                name: name.as_ref().to_string(),
                dtype,
            })
    }
    /// return all profile names
    pub fn all(&self) -> Vec<String> {
        self.profiles.keys().cloned().collect()
    }
    pub fn remove<S: AsRef<str>>(&mut self, name: S) -> Option<Profile> {
        self.profiles.remove(name.as_ref()).map(|dtype| Profile {
            name: name.as_ref().to_string(),
            dtype,
        })
    }
    pub fn get_current(&self) -> Option<Profile> {
        self.get(self.current_profile.as_str())
    }
    pub fn set_current(&mut self, pf: Profile) {
        assert!(
            self.get(&pf.name).is_some(),
            "Selected profile not found in database"
        );
        self.current_profile = pf.name;
    }
}

#[cfg(test)]
mod test {
    use super::*;
    #[test]
    fn serde() {
        let mut db = ProfileManager {
            current_profile: "".to_string().into(),
            profiles: ProfileDataBase::new().into(),
        };
        db.insert("pf1", ProfileType::File);
        db.insert("pf2", ProfileType::Generated("template1".to_string()));
        db.insert(
            "pf3",
            ProfileType::Github {
                url: "https://github.com".to_string(),
                token: "Token".to_string(),
            },
        );
        db.insert(
            "pf4",
            ProfileType::GitLab {
                url: "https://gitlab.com".to_string(),
                token: "Token".to_string(),
            },
        );
        db.insert("pf5", ProfileType::Url("https://raw.com".to_string()));
        let serde = r#"current_profile: ''
profiles:
  pf5: !Url https://raw.com
  pf2: !Generated template1
  pf4: !GitLab
    url: https://gitlab.com
    token: Token
  pf1: File
  pf3: !Github
    url: https://github.com
    token: Token
"#;
        let serde: ProfileManager = serde_yml::from_str(serde).unwrap();
        assert_eq!(db, serde);
    }
}
