name: Pull Request

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CLASHTUI_VERSION: ${{ github.head_ref }}

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Mihomo
        run: |
          wget --output-document mihomo.gz https://github.com/MetaCubeX/mihomo/releases/download/v1.18.4/mihomo-linux-amd64-v1.18.4.gz
          gunzip mihomo.gz
          chmod +x mihomo
          nohup ./mihomo -d Example -f Example/basic_clash_config.yaml &

      - name: Download Dependencies
        run: cd clashtui && cargo fetch

      - name: Build
        run: cd clashtui && cargo build --verbose

      - name: Run tests
        run: cd clashtui && cargo test --all --verbose

      - name: Build Version
        run: cd clashtui && cargo r -- -v

      - name: Pre Upload
        run: |
          mkdir artifacts
          mv ./clashtui/target/debug/clashtui ./artifacts/clashtui.debug

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux_Build
          path: artifacts
          retention-days: 5

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Mihomo
        run: |
          curl -L https://github.com/MetaCubeX/mihomo/releases/download/v1.18.4/mihomo-windows-amd64-v1.18.4.zip --output mihomo.zip 
          7z x mihomo.zip
          mihomo-windows-amd64.exe -d Example -f Example/basic_clash_config.yaml &

      - name: Download Dependencies
        run: cd clashtui && cargo fetch

      - name: Build
        run: cd clashtui && cargo build --verbose && cargo build --release

      # - name: Run tests
      #   run: cd clashtui && cargo test --all --verbose

      - name: Build Version
        run: cd clashtui && cargo r -- -v

      - name: Pre Upload
        run: |
          mkdir artifacts
          mv ./clashtui/target/debug/clashtui.exe ./artifacts/clashtui.debug.exe

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows_Build
          path: artifacts
          retention-days: 5
