name: Pull Request

on:
  pull_request:
    branches:
      - demotui
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'build.rs'

env:
  CARGO_TERM_COLOR: always
  CLASHTUI_VERSION: ${{ github.head_ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2

      - name: Download Dependencies
        run: cargo fetch

      - name: Run tests
        run: cargo test --all --verbose

      - name: Build
        run: |
          rustup target add x86_64-unknown-linux-gnu
          cargo install cargo-zigbuild
          cargo zigbuild --target x86_64-unknown-linux-gnu.2.17 --verbose

      - name: Build Version
        run: ./target/x86_64-unknown-linux-gnu/debug/clashtui --version

      - name: Pre Upload
        run: |
          mkdir artifacts
          mv ./target/x86_64-unknown-linux-gnu/debug/clashtui ./artifacts/clashtui.debug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux_Build
          path: artifacts
          retention-days: 5
